source :gemcutter
# source :rubygems
# source :rubyforge

gem 'awesome_print'
gem 'bundler'
gem 'cheat'
gem 'git_remote_branch'
gem 'github'
gem 'irb_hacks'
gem 'open_gem'
gem 'ori'
gem 'powder'
gem 'powify'
gem 'rake'
gem 'rdoc'
gem 'showoff-io'
gem 'wirble'
